grpc:
  host: 0.0.0.0
  port: 50051

database:
  url: postgres://user:password@localhost/dbname
  max_connections: 10

log_level: info

feature_flags:
  enable_analytics: true
  enable_cache: false

markets:
  - name: BTC/USD
    base: BTC
    quote: USD
    amount_prec: 8
    price_prec: 2
    fee_prec: 4
    min_amount: 0.001
  - name: ETH/USD
    base: ETH
    quote: USD
    amount_prec: 6
    price_prec: 2
    fee_prec: 4
    min_amount: 0.01
